use_frameworks! :linkage => :static
platform :ios, '13.4'  # or whatever minimum iOS version you're targeting
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


target 'auratalk_app' do
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Add any additional pods your project needs here
  # For example:
  # pod 'SomeExternalLibrary'

  target 'auratalk_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    #__apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
